name: Build .NET Console Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release

    - name: Publish application
      run: dotnet publish --configuration Release --self-contained --runtime win-x64 --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Published Application
        path: ./publish
